=== 17Greninja/Ontology/Group 7_Assignment 1/hotel.dtd
<?xml version="1.0" encoding="UTF-8"?>

<!ELEMENT hotel (name,address,phNo+,website?,email_id,dept+,room+,customer*,service*,amenity*)>
<!ATTLIST hotel hotel_id ID #REQUIRED>
<!ATTLIST hotel rating (1|2|3|4|5) #IMPLIED>

<!ELEMENT name (#PCDATA)>

<!ELEMENT address (street,city,state,pincode?)>
<!ELEMENT street (#PCDATA)>
<!ELEMENT city (#PCDATA)>
<!ELEMENT state (#PCDATA)>
<!ELEMENT pincode (#PCDATA)>

<!ELEMENT website (#PCDATA)>
<!ELEMENT email_id (#PCDATA)>
<!ELEMENT phNo (#PCDATA)>

<!ELEMENT dept (name, phNo, employee+)>
<!ATTLIST dept dept_id ID #REQUIRED>
<!ATTLIST dept head IDREF #REQUIRED>

<!ELEMENT employee (name, address, phNo, login_detail, role, assistant?)>
<!ATTLIST employee emp_id ID #REQUIRED>
<!ELEMENT assistant (employee)>

<!ELEMENT login_detail EMPTY>
<!ATTLIST login_detail login_id ID #REQUIRED>
<!ATTLIST login_detail password CDATA #REQUIRED>

<!ELEMENT role (#PCDATA)>

<!ELEMENT customer (name, phNo, address, email_id, reservation+)>
<!ATTLIST customer cust_id ID #REQUIRED>

<!ELEMENT reservation (date_in,date_out,res_date)>
<!ATTLIST reservation res_id ID #REQUIRED>
<!ATTLIST reservation room IDREF #REQUIRED>

<!ELEMENT room (room_type)>
<!ATTLIST room room_no ID #REQUIRED>
<!ATTLIST room floor CDATA #REQUIRED>

<!ELEMENT room_type EMPTY>
<!ATTLIST room_type type (luxury|regular) "regular">
<!ATTLIST room_type cost CDATA "10000">

<!ELEMENT date_in (#PCDATA)>
<!ELEMENT date_out (#PCDATA)>
<!ELEMENT res_date (#PCDATA)>

<!ELEMENT service EMPTY>
<!ATTLIST service service_id ID #REQUIRED>
<!ATTLIST service service_name CDATA #REQUIRED>
<!ATTLIST service cost CDATA #REQUIRED>

<!ELEMENT amenity (name,booking*)>
<!ATTLIST amenity max_capacity CDATA #IMPLIED>

<!ELEMENT booking (name, date, slot, no_of_ppl)>
<!ATTLIST booking booking_id ID #REQUIRED>
<!ATTLIST booking cust_id IDREF #REQUIRED>
<!ELEMENT date (#PCDATA)>
<!ELEMENT no_of_ppl (#PCDATA)>
<!ELEMENT slot EMPTY>
<!ATTLIST slot duration_hrs CDATA #FIXED "1">
<!ATTLIST slot time CDATA #REQUIRED>
 
<!ENTITY reg_cost "10000">
<!ENTITY med_cost "15000">
<!ENTITY lux_cost "20000">

=== 17Greninja/Ontology/Group 7_Assignment 1/hotel.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE hotel SYSTEM 'hotel.dtd'>
<hotel hotel_id="AEf1123" rating="4">
  <name>The Grand IITians Hotel</name>
  <address>
    <street> Gajendra Circle </street>
    <city>Chennai</city>
    <state>Tamil Nadu</state>
    <pincode>600036</pincode>
  </address>
  <phNo>+91 9878065214</phNo>
  <phNo>04345665004</phNo>
  <website>thegrandiithotel.com</website>
  <email_id>info@thegrandiithotel.com</email_id>
  <dept dept_id="D1" head="E100">
    <name>Office</name>
    <phNo>111111</phNo>
    <employee emp_id="E100">
      <name>oleg</name>
      <address>
        <street>Room 1</street>
        <city>Chennai</city>
        <state>Tamil Nadu</state>
      </address>
      <phNo>1111111</phNo>
      <login_detail login_id="L100" password="password1"/>
      <role>Supervisor</role>
      <assistant>
        <employee emp_id="E1000">
          <name>Mahesh</name>
          <address>
            <street>Banjara Hills</street>
            <city>Hyderabad</city>
            <state>Andhra Pradesh</state>
          </address>
          <phNo>9087656231</phNo>
          <login_detail login_id="L1000" password="gfyftf"/>
          <role>Assistant</role>
        </employee>
      </assistant>
    </employee>
    <employee emp_id="E101">
      <name>omar</name>
      <address>
        <street>Room 2</street>
        <city>Chennai</city>
        <state>Tamil Nadu</state>
      </address>
      <phNo>1111112</phNo>
      <login_detail login_id="L101" password="password2"/>
      <role>Lady Clerk</role>

    </employee>
    <employee emp_id="E102">
      <name>alex</name>
      <address>
        <street>Room 3</street>
        <city>Chennai</city>
        <state>Tamil Nadu</state>
      </address>
      <phNo>1111113</phNo>
      <login_detail login_id="L102" password="password3"/>
      <role>Lady Clerk</role>

    </employee>
    <employee emp_id="E103">
      <name>abdul</name>
      <address>
        <street>Room 4</street>
        <city>Chennai</city>
        <state>Tamil Nadu</state>
      </address>
      <phNo>1111114</phNo>
      <login_detail login_id="L103" password="password4"/>
      <role>Male Clerk</role>

    </employee>
    <employee emp_id="E104">
      <name>albert</name>
      <address>
        <street>Room 5</street>
        <city>Chennai</city>
        <state>Tamil Nadu</state>
      </address>
      <phNo>1111115</phNo>
      <login_detail login_id="L104" password="password5"/>
      <role>Receptionist</role>

    </employee>
    <employee emp_id="E105">
      <name>andrew</name>
      <address>
        <street>Room 6</street>
        <city>Chennai</city>
        <state>Tamil Nadu</state>
      </address>
      <phNo>1111116</phNo>
      <login_detail login_id="L105" password="password6"/>
      <role>Receptionist</role>

    </employee>
  </dept>
  <dept dept_id="D2" head="E200">
    <name>Housekeeping</name>
    <phNo>222222</phNo>
    <employee emp_id="E200">
      <name>hamza</name>
      <address>
        <street>Room 7</street>
        <city>Chennai</city>
        <state>Tamil Nadu</state>
      </address>
      <phNo>2111111</phNo>
      <login_detail login_id="L200" password="password7"/>
      <role>Supervisor</role>
      <assistant>
        <employee emp_id="E1001">
          <name>Karthik</name>
          <address>
            <street>Gandhi Street</street>
            <city>Kochi</city>
            <state>Kerala</state>
          </address>
          <phNo>6767890123</phNo>
          <login_detail login_id="L1001" password="gyugyufu"/>
          <role>Assistant</role>
        </employee>
      </assistant>
    </employee>
    <employee emp_id="E201">
      <name>hanif</name>
      <address>
        <street>Room 8</street>
        <city>Chennai</city>
        <state>Tamil Nadu</state>
      </address>
      <phNo>2111112</phNo>
      <login_detail login_id="L201" password="password8"/>
      <role>Toilet Cleaner</role>

    </employee>
    <employee emp_id="E202">
      <name>hannah</name>
      <address>
        <street>Room 9</street>
        <city>Chennai</city>
        <state>Tamil Nadu</state>
      </address>
      <phNo>2111113</phNo>
      <login_detail login_id="L202" password="password9"/>
      <role>Maid</role>

    </employee>
    <employee emp_id="E203">
      <name>bob</name>
      <address>
        <street>Room 10</street>
        <city>Chennai</city>
        <state>Tamil Nadu</state>
      </address>
      <phNo>2111114</phNo>
      <login_detail login_id="L203" password="password0"/>
      <role>Maid</role>

    </employee>
    <employee emp_id="E204">
      <name>bradley</name>
      <address>
        <street>Room 11</street>
        <city>Chennai</city>
        <state>Tamil Nadu</state>
      </address>
      <phNo>2111115</phNo>
      <login_detail login_id="L204" password="password1"/>
      <role>Toilet Cleaner</role>

    </employee>
    <employee emp_id="E205">
      <name>carrie</name>
      <address>
        <street>Room 12</street>
        <city>Chennai</city>
        <state>Tamil Nadu</state>
      </address>
      <phNo>2111116</phNo>
      <login_detail login_id="L205" password="password2"/>
      <role>Toiler</role>

    </employee>
    <employee emp_id="E206">
      <name>carraugh</name>
      <address>
        <street>Room 13</street>
        <city>Chennai</city>
        <state>Tamil Nadu</state>
      </address>
      <phNo>2111117</phNo>
      <login_detail login_id="L206" password="password3"/>
      <role>Floor Cleaner</role>

    </employee>
    <employee emp_id="E207">
      <name>carmen</name>
      <address>
        <street>Room 14</street>
        <city>Chennai</city>
        <state>Tamil Nadu</state>
      </address>
      <phNo>2111118</phNo>
      <login_detail login_id="L207" password="password4"/>
      <role>Floor Cleaner</role>

    </employee>
    <employee emp_id="E208">
      <name>connie</name>
      <address>
        <street>Room 15</street>
        <city>Chennai</city>
        <state>Tamil Nadu</state>
      </address>
      <phNo>2111119</phNo>
      <login_detail login_id="L208" password="password5"/>
      <role>Floor Cleaner</role>

    </employee>
    <employee emp_id="E209">
      <name>kathy</name>
      <address>
        <street>Room 16</street>
        <city>Chennai</city>
        <state>Tamil Nadu</state>
      </address>
      <phNo>2111120</phNo>
      <login_detail login_id="L209" password="password6"/>
      <role>Toilet Cleaner</role>

    </employee>
    <employee emp_id="E210">
      <name>krirsten</name>
      <address>
        <street>Room 17</street>
        <city>Chennai</city>
        <state>Tamil Nadu</state>
      </address>
      <phNo>211121</phNo>
      <login_detail login_id="L210" password="password7"/>
      <role>Floor Cleaner</role>

    </employee>
  </dept>
  <dept dept_id="D3" head="E300">
    <name>Kitchen</name>
    <phNo>333333</phNo>
    <employee emp_id="E300">
      <name>debbie</name>
      <address>
        <street>Room 18</street>
        <city>Chennai</city>
        <state>Tamil Nadu</state>
      </address>
      <phNo>3111111</phNo>
      <login_detail login_id="L300" password="password8"/>
      <role>Supervisor</role>
      <assistant>
        <employee emp_id="E1002">
          <name>Prabhas</name>
          <address>
            <street>Palace Road</street>
            <city>Maheshmati</city>
            <state>Telengana</state>
          </address>
          <phNo>7337509366</phNo>
          <login_detail login_id="L1002" password="iuweufhwue"/>
          <role>Assistant</role>
        </employee>
      </assistant>
    </employee>
    <employee emp_id="E301">
      <name>donna</name>
      <address>
        <street>Room 19</street>
        <city>Chennai</city>
        <state>Tamil Nadu</state>
      </address>
      <phNo>3111112</phNo>
      <login_detail login_id="L301" password="password9"/>
      <role>Porter</role>

    </employee>
    <employee emp_id="E302">
      <name>david</name>
      <address>
        <street>Room 20</street>
        <city>Chennai</city>
        <state>Tamil Nadu</state>
      </address>
      <phNo>3111113</phNo>
      <login_detail login_id="L302" password="0password"/>
      <role>Head Chef</role>

    </employee>
    <employee emp_id="E303">
      <name>dick</name>
      <address>
        <street>Room 21</street>
        <city>Chennai</city>
        <state>Tamil Nadu</state>
      </address>
      <phNo>3111114</phNo>
      <login_detail login_id="L303" password="1password"/>
      <role>Head Chef</role>

    </employee>
    <employee emp_id="E304">
      <name>dave</name>
      <address>
        <street>1st Street, KK Nagar</street>
        <city>Chennai</city>
        <state>Tamil Nadu</state>
      </address>
      <phNo>3111115</phNo>
      <login_detail login_id="L304" password="2password"/>
      <role>Sous Chef</role>

    </employee>
    <employee emp_id="E305">
      <name>dilbert</name>
      <address>
        <street>Lane 23</street>
        <city>Chennai</city>
        <state>Tamil Nadu</state>
      </address>
      <phNo>3111116</phNo>
      <login_detail login_id="L305" password="3password"/>
      <role>Manager</role>

    </employee>
    <employee emp_id="E306">
      <name>douglas</name>
      <address>
        <street>3rd Cross Street</street>
        <city>Bangalore</city>
        <state>Karnataka</state>
      </address>
      <phNo>3111117</phNo>
      <login_detail login_id="L306" password="4password"/>
      <role>Station Chef</role>

    </employee>
  </dept>
  <dept dept_id="D4" head="E400">
    <name>Security</name>
    <phNo>444444</phNo>
